apiVersion: v1
kind: ReplicationController
metadata:
  name: myjenkins-rc
spec:
  replicas: 3
  selector:
     app: myjavaapp-pod
     template:
       metadata:
       labels:
          app: myjenkins-pod
    spec:
      containers:
      - name: myjenkins-container
        image: jenkins:2.60.3
        ports:
        - containerPort: 8080